### ISSUE TITLE
Is it really (PO)MDPs...?

### ISSUE THREAD

**Issue by Rowing0914** [RedBanies3ofThem/recommendation-gym#1]
Thank you for your contribution to the community! Personally, I found your neat implementation interesting and helpful!
By the way, is this current implementation following the Markov Property?
For instance, in MDPs, there is a state transition showing P(s' | s, a), right? And in RecSys setting, the state space consists of static and dynamic properties of users such as Static(User profile, eg., gender/age etc) and Dynamic(User's past activity, eg., click/non-click or view/purchase etc) so that we can correlate the states based on the action taken by an agent.

Looking at this implementation, it literally calculates the average of the ratings which I think it isn't dynamic over time and irrelevant to the occurrence of actions. could you help understand this part...?

## Code
https://github.com/sadighian/recommendation-gym/blob/master/gym_recommendation/envs/reco_env.py#L207-L208

**Comment by R-Ceph** [comment]
You Are Absolutely Right!
